export const CAT_LIST_REQUEST = 'CAT_LIST_REQUEST';
export const CAT_LIST_SUCCESS = 'CAT_LIST_SUCCESS';
export const CAT_LIST_FAIL = 'CAT_LIST_FAIL';
export const CAT_PRODUCT_LIST_REQUEST = 'CAT_PRODUCT_LIST_REQUEST';
export const CAT_PRODUCT_LIST_SUCCESS = 'CAT_PRODUCT_LIST_SUCCESS';
export const CAT_PRODUCT_LIST_FAIL = 'CAT_LIST_FAIL';
